# Generated by Django 4.2.13 on 2024-05-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='slag',
            new_name='slug',
        ),
    ]
