# Generated by Django 4.2.13 on 2024-06-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_slag_categories_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
